# Local place to keep things that would otherwise be set by environment
# variables in production for use in places like secrets.yml.
#
# Copy this to config/application.yml to use it.  It will not be committed
# to the repo.

GOOGLE_CLIENT_ID: "SET GOOGLE CLIENT ID HERE"
GOOGLE_CLIENT_SECRET: "SET GOOGLE CLIENT SECRET HERE"
