# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efd69b036a4c31c05dd78a4e13658c2570254a8559b721206239e396c944c552b667e0b100c2f8153356e02a790e33fbd19c25a72ca959d12303bdfa68ea39f5

test:
  secret_key_base: 230ce321afd7c273721ab4dc3287c9e05287f3f0fd384c9618dc131abad4e6c98cf8f414e19f28c9294dab6af7bed00cf4ca8a8f39456dc6cb15834c58320c79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
